
env:
   global:
     - CONAN_REFERENCE: "waf/2.0.17@czoido/testing"
     - CONAN_USERNAME: "czoido"
     - CONAN_LOGIN_USERNAME: "czoido"
     - CONAN_CHANNEL: "stable"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/czoido/conan-packages"
     - CONAN_REMOTES: "https://api.bintray.com/conan/czoido/conan-packages@True@czoido-bintray"

linux: &linux
   os: linux
   dist: xenial
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:

      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=conanio/gcc6 CONAN_ARCHS=x86_64

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh